node_js:
- "0.10"
script: node node_modules/intern/runner.js config=tests/intern
language: node_js
env:
    global:
        secure: "KB1y3ZTTmdaukA27IZCF5XXx6tpHj/J0/beka4rkFi3lgGVJP9Dn5/XZYvy4\nRTnMzL8j+QFtpg+3WTgu072novpA3rjeSlM8IHQmd+7JlfV3ayceeckGCfde\nZogMox5pk0vT7N6Gxe5hjiFEObrKqKnzhkqhV1RkLqIWJ6EIEc0="